In [8]:
import numpy as np
import pandas as pd
import itertools

In [9]:
data = pd.read_table("data\\imdb-title-cast-rating-desc.tsv")
data = data.dropna()
data = data[data["genre"]!="\\N"]

,index,tconst,titleType,title,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genre,cast,rating,description
0,0,tt0032557,tvSeries,The Green Archer,The Green Archer,0,1940,\N,285,"Action,Adventure,Crime",nm0345300 nm0430460 nm0580585 nm0186608 nm0279...,6.6,Columbia's 12th serial of 57 total (following ...
1,1,tt0035803,tvSeries,The German Weekly Review,Die Deutsche Wochenschau,0,1940,1945,12,"Documentary,News",nm0324305 nm0351425 nm0381523 nm0386944 nm2233...,7.7,News of the Week: German Troops Capture Rome; ...
2,2,tt0039120,tvSeries,Americana,Americana,0,1947,1949,30,"Family,Game-Show",nm0564535 nm0175091 nm0202565 nm0272126 nm0304...,3.0,Americana is a weekly game show which ran on N...
3,3,tt0039123,tvSeries,Kraft Theatre,Kraft Television Theatre,0,1947,1958,60,Drama,nm0572844 nm0379051 nm0853299 nm0181961 nm0550...,8.4,Kraft Television Theatre is an American drama/...
4,5,tt0040021,tvSeries,Actor's Studio,Actor's Studio,0,1948,1950,30,Drama,nm0384696 nm0175091 nm1169111 nm0358449 nm0291...,7.1,Actors Studio is an American TV show which air...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
27303,70953,tt9906902,tvSeries,History Erased,History Erased,0,2019,2021,60,Documentary,nm8943457 nm4953926 nm6177643 nm11776042 nm102...,6.6,A fascinating documentary series that celebrat...
27304,70956,tt9908860,tvSeries,Blown Away,Blown Away,0,2019,\N,23,Reality-TV,nm4903469 nm4509752 nm5998859 nm11261411 nm112...,7.1,Ten master artists turn up the heat in glassbl...
27305,70957,tt9909248,tvSeries,Race Across the World,Race Across the World,0,2019,\N,59,"Documentary,Game-Show",nm11551632 nm11551612 nm11551633 nm11551611 nm...,8.3,Pairs of travellers race to reach the Far East...
27306,70967,tt9910728,tvSeries,Zalim Istanbul,Zalim Istanbul,0,2019,2020,120,Drama,nm8823972 nm0476334 nm1728957 nm7487579 nm9619...,5.7,The life of a disabled guy changes dramaticall...
27307,70973,tt9915156,tvSeries,Tree in the River,Tree in the River,0,2018,\N,\N,Drama,nm1239735 nm3170288 nm3485729 nm2431533 nm2978...,6.0,Chu Zhi He who's a goodie two shoes and Wang D...

In [10]:
show_genres = list(data["genre"])

genres = ",".join(show_genres)
genres = genres.split(",")
genres = set(genres)

In [11]:

print(len(genres))
print(genres)

27
{'Music', 'Drama', 'Adventure', 'Sci-Fi', 'Thriller', 'Biography', 'Horror', 'Adult', 'Crime', 'War', 'Comedy', 'Talk-Show', 'News', 'History', 'Short', 'Documentary', 'Game-Show', 'Mystery', 'Romance', 'Action', 'Fantasy', 'Sport', 'Reality-TV', 'Animation', 'Family', 'Western', 'Musical'}

In [16]:
sum = 0
sqs = 0
for genre in genres:
    df = data[data["genre"].str.contains(genre)]
    rows = df.shape[0]
    # print(genre, rows)
    sum += rows 
    sqs += rows * rows
print("Sum =",sum)
print("Sq =",sqs)

Sum = 50518
Sq = 235575140

In [24]:
mega_set = set()


for genre in genres:
    print(genre)
    df = data[data["genre"].str.contains(genre)]
    titles = df["title"]
    for t1 in titles:
        for t2 in titles:
            if t1 != t2:
                mega_set.add(tuple(sorted([t1,t2])))

Music
Drama
Adventure
Sci-Fi
Thriller
Biography
Horror
Adult
Crime
War
Comedy
Talk-Show
News
History
Short
Documentary
Game-Show
Mystery
Romance
Action
Fantasy
Sport
Reality-TV
Animation
Family
Western
Musical

In [25]:
print(len(mega_set))

100585743

In [ ]:

# mega_list = []
# sum = 0
# for genre in genres:
#     print(genre)
#     df = data[data["genre"].str.contains(genre)]
#     titles = df["title"]
#     l = len(list(itertools.product(titles,titles)))
#     print(l)
#     sum += l
# print(sum)

In [ ]:

"""
'Music'
'Drama'
'Adventure'
'Sci-Fi'
'Thriller'
'Biography'
'Horror'
'Adult'
'Crime'
'War'
'Comedy'
'Talk-Show'
'News'
'History'
'Short'
'Documentary'
'Game-Show'
'Mystery'
'Romance'
'Action'
'Fantasy'
'Sport'
'Reality-TV'
'Animation'
'Family'
'Western'
'Musical'
"""